language: csharp
mono: none
script:
  - wget -q https://packages.microsoft.com/config/ubuntu/14.04/packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get install apt-transport-https
  - sudo apt-get update
  - sudo apt-get install dotnet-sdk-2.2
  - sudo dotnet restore
  - sudo dotnet build ./LlvmSharpLang/
  - sudo dotnet build ./LlvmSharpLang.Tests/
  - sudo dotnet test ./LlvmSharpLang.Tests/
